name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Insert <base> tag before <title> with full path (in /docs)
        working-directory: ./docs
        run: |
          for filepath in $(find . -name "*.html"); do
            if ! grep -q '<base href=' "$filepath"; then
              relative_path=${filepath#./}
              full_url="https://xiaopinggao.github.io/aitutor/${relative_path}"
              sed -i '/<title/ i\<base href="'"$full_url"'">' "$filepath"
            fi
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs